/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from "@icp-sdk/core/agent";
import type { IDL } from "@icp-sdk/core/candid";
import type { Principal } from "@icp-sdk/core/principal";

/**
 * Represents an account on the ckDOGE ledger.
 */
export interface Account {
  owner: Principal;
  subaccount: [] | [Uint8Array];
}
export interface CanisterStatusResponse {
  memory_metrics: MemoryMetrics;
  status: CanisterStatusType;
  memory_size: bigint;
  ready_for_migration: boolean;
  version: bigint;
  cycles: bigint;
  settings: DefiniteCanisterSettings;
  query_stats: QueryStats;
  idle_cycles_burned_per_day: bigint;
  module_hash: [] | [Uint8Array];
  reserved_cycles: bigint;
}
export type CanisterStatusType =
  | { stopped: null }
  | { stopping: null }
  | { running: null };
export interface ChangeOutput {
  value: bigint;
  vout: number;
}
export interface ConsolidateUtxosRequest {
  received_at: bigint;
  block_index: bigint;
  address: DogecoinAddress;
  amount: bigint;
}
export interface DefiniteCanisterSettings {
  freezing_threshold: bigint;
  wasm_memory_threshold: bigint;
  environment_variables: Array<environment_variable>;
  controllers: Array<Principal>;
  reserved_cycles_limit: bigint;
  log_visibility: log_visibility;
  wasm_memory_limit: bigint;
  memory_allocation: bigint;
  compute_allocation: bigint;
}
export type DogecoinAddress = { P2pkh: Uint8Array } | { P2sh: Uint8Array };
export type EstimateWithdrawalFeeError =
  | {
      /**
       * The current withdrawal amount is too high so that either the minter does not have enough
       * funds to satisfy that request; or, it would use too many UTXOs so that the transaction may be
       * non-standard.
       */
      AmountTooHigh: null;
    }
  | {
      /**
       * The given withdrawal amount is too low to pay for the transaction and minter fee.
       * The minimum withdrawal amount may vary depending on the current transaction fees.
       */
      AmountTooLow: { min_amount: bigint };
    };
export interface Event {
  timestamp: [] | [bigint];
  payload: EventType;
}
export type EventType =
  | {
      received_utxos: {
        to_account: Account;
        mint_txid: [] | [bigint];
        utxos: Array<Utxo>;
      };
    }
  | { removed_retrieve_doge_request: { block_index: bigint } }
  | {
      sent_transaction: {
        fee: [] | [bigint];
        change_output: [] | [ChangeOutput];
        txid: Uint8Array;
        signed_tx: [] | [Uint8Array];
        withdrawal_fee: [] | [WithdrawalFee];
        utxos: Array<Utxo>;
        requests: BigUint64Array;
        submitted_at: bigint;
      };
    }
  | { init: InitArgs }
  | { upgrade: UpgradeArgs }
  | {
      suspended_utxo: {
        utxo: Utxo;
        account: Account;
        reason: SuspendedReason;
      };
    }
  | { checked_utxo: { utxo: Utxo; account: Account } }
  | { accepted_retrieve_doge_request: RetrieveDogeRequest }
  | {
      schedule_withdrawal_reimbursement: {
        burn_block_index: bigint;
        account: Account;
        amount: bigint;
        reason: WithdrawalReimbursementReason;
      };
    }
  | { quarantined_withdrawal_reimbursement: { burn_block_index: bigint } }
  | { confirmed_transaction: { txid: Uint8Array } }
  | {
      replaced_transaction: {
        fee: bigint;
        change_output: ChangeOutput;
        new_utxos: [] | [Array<Utxo>];
        old_txid: Uint8Array;
        withdrawal_fee: [] | [WithdrawalFee];
        new_txid: Uint8Array;
        submitted_at: bigint;
        reason: [] | [ReplacedReason];
      };
    }
  | { checked_utxo_mint_unknown: { utxo: Utxo; account: Account } }
  | { created_consolidate_utxos_request: ConsolidateUtxosRequest }
  | {
      reimbursed_withdrawal: {
        burn_block_index: bigint;
        mint_block_index: bigint;
      };
    };
/**
 * The initialization parameters of the minter canister.
 */
export interface InitArgs {
  /**
   * The expiration duration (in seconds) for cached entries in the get_utxos cache.
   */
  get_utxos_cache_expiration_seconds: [] | [bigint];
  /**
   * The minimal amount of ckDOGE that can be converted to DOGE.
   */
  retrieve_doge_min_amount: bigint;
  /**
   * The name of the ECDSA key to use.
   * E.g., "dfx_test_key" on the local replica.
   */
  ecdsa_key_name: string;
  /**
   * The minter's operation mode.
   */
  mode: Mode;
  /**
   * The principal of the ledger that handles ckDOGE transfers.
   * The default account of the ckDOGE minter must be configured as
   * the minting account of the ledger.
   */
  ledger_id: Principal;
  /**
   * Maximum time in nanoseconds that a transaction should spend in the queue
   * before being sent.
   */
  max_time_in_queue_nanos: bigint;
  /**
   * / The maximum number of input UTXOs allowed in a transaction.
   */
  max_num_inputs_in_transaction: [] | [bigint];
  /**
   * / The minimum number of available UTXOs to trigger a consolidation.
   */
  utxo_consolidation_threshold: [] | [bigint];
  /**
   * The minter will interact with this Dogecoin network.
   */
  doge_network: Network;
  /**
   * The minimum number of confirmations required for the minter to
   * accept a Dogecoin transaction.
   */
  min_confirmations: [] | [number];
  /**
   * The minimal amount of DOGE that can be converted to ckDOGE.
   * UTXOs with lower values will be ignored.
   */
  deposit_doge_min_amount: [] | [bigint];
}
export type InvalidTransactionError = {
  too_many_inputs: { max_num_inputs: bigint; num_inputs: bigint };
};
export interface MemoryMetrics {
  wasm_binary_size: bigint;
  wasm_chunk_store_size: bigint;
  canister_history_size: bigint;
  stable_memory_size: bigint;
  snapshots_size: bigint;
  wasm_memory_size: bigint;
  global_memory_size: bigint;
  custom_sections_size: bigint;
}
export type MinterArg = { Upgrade: [] | [UpgradeArgs] } | { Init: InitArgs };
export interface MinterInfo {
  /**
   * This amount is based on the `retrieve_doge_min_amount` setting during canister
   * initialization or upgrades, but may vary according to current network fees.
   */
  retrieve_doge_min_amount: bigint;
  /**
   * The minimum number of confirmations required for the minter to
   * accept a Dogecoin transaction.
   */
  min_confirmations: number;
  /**
   * Minimal amount of DOGE that can be deposited to be converted into ckDOGE.
   * UTXOs with lower values will be ignored.
   */
  deposit_doge_min_amount: bigint;
}
export type Mode =
  | {
      /**
       * Only specified principals can modify minter's state.
       */
      RestrictedTo: Array<Principal>;
    }
  | {
      /**
       * Only specified principals can convert DOGE to ckDOGE.
       */
      DepositsRestrictedTo: Array<Principal>;
    }
  | {
      /**
       * The minter does not allow any state modifications.
       */
      ReadOnly: null;
    }
  | {
      /**
       * Anyone can interact with the minter.
       */
      GeneralAvailability: null;
    };
export type Network =
  | {
      /**
       * The public Dogecoin mainnet.
       */
      Mainnet: null;
    }
  | {
      /**
       * A local Dogecoin regtest installation.
       */
      Regtest: null;
    };
/**
 * Utxos that don't have enough confirmations to be processed.
 */
export interface PendingUtxo {
  confirmations: number;
  value: bigint;
  outpoint: { txid: Uint8Array; vout: number };
}
export interface QueryStats {
  response_payload_bytes_total: bigint;
  num_instructions_total: bigint;
  num_calls_total: bigint;
  request_payload_bytes_total: bigint;
}
export interface ReimbursedDeposit {
  account: Account;
  mint_block_index: bigint;
  amount: bigint;
  reason: ReimbursementReason;
}
export type ReimbursementReason =
  | { CallFailed: null }
  | { TaintedDestination: { kyt_fee: bigint; kyt_provider: Principal } };
export interface ReimbursementRequest {
  account: Account;
  amount: bigint;
  reason: ReimbursementReason;
}
export type ReplacedReason =
  | {
      to_cancel: { reason: WithdrawalReimbursementReason };
    }
  | { to_retry: null };
export interface RetrieveDogeOk {
  /**
   * Returns the burn transaction index corresponding to the withdrawal.
   * You can use this index to query the withdrawal status.
   */
  block_index: bigint;
}
export interface RetrieveDogeRequest {
  received_at: bigint;
  block_index: bigint;
  address: DogecoinAddress;
  reimbursement_account: [] | [Account];
  amount: bigint;
}
export type RetrieveDogeStatus =
  | {
      /**
       * The minter is obtaining all required ECDSA signatures on the
       * Dogecoin transaction for this request.
       */
      Signing: null;
    }
  | {
      /**
       * The minter received enough confirmations for the Dogecoin
       * transaction for this request.  The payload contains the
       * identifier of the transaction on the Dogecoin network.
       */
      Confirmed: { txid: Uint8Array };
    }
  | {
      /**
       * The minter signed the transaction and is waiting for a reply
       * from the Dogecoin canister.
       */
      Sending: { txid: Uint8Array };
    }
  | {
      /**
       * The amount was too low to cover the transaction fees.
       */
      AmountTooLow: null;
    }
  | {
      /**
       * The minter will try to reimburse this transaction.
       */
      WillReimburse: ReimbursementRequest;
    }
  | {
      /**
       * The minter does not have any information on the specified
       * retrieval request.  It can be that nobody submitted the
       * request or the minter pruned the relevant information from the
       * history to save space.
       */
      Unknown: null;
    }
  | {
      /**
       * The minter sent a transaction for the retrieve request.
       * The payload contains the identifier of the transaction on the Dogecoin network.
       */
      Submitted: { txid: Uint8Array };
    }
  | {
      /**
       * The retrieve Dogecoin request has been reimbursed.
       */
      Reimbursed: ReimbursedDeposit;
    }
  | {
      /**
       * The minter did not send a Dogecoin transaction for this request yet.
       */
      Pending: null;
    };
export interface RetrieveDogeWithApprovalArgs {
  /**
   * The subaccount to burn ckDOGE from.
   */
  from_subaccount: [] | [Uint8Array];
  /**
   * The address to which the ckDOGE minter should deposit DOGE.
   */
  address: string;
  /**
   * The amount of ckDOGE in koinu (smallest denomination of DOGE) that the client wants to withdraw.
   */
  amount: bigint;
}
export type RetrieveDogeWithApprovalError =
  | {
      /**
       * The minter failed to parse the destination address.
       */
      MalformedAddress: string;
    }
  | {
      /**
       * A generic error reserved for future extensions.
       */
      GenericError: { error_message: string; error_code: bigint };
    }
  | {
      /**
       * The minter is overloaded, retry the request.
       * The payload contains a human-readable message explaining what caused the unavailability.
       */
      TemporarilyUnavailable: string;
    }
  | {
      /**
       * The allowance given to the minter is too low.
       */
      InsufficientAllowance: { allowance: bigint };
    }
  | {
      /**
       * The minter is already processing another retrieval request for the same
       * principal.
       */
      AlreadyProcessing: null;
    }
  | {
      /**
       * The withdrawal amount is too low.
       * The payload contains the minimal withdrawal amount.
       */
      AmountTooLow: bigint;
    }
  | {
      /**
       * The ckDOGE balance of the withdrawal account is too low.
       */
      InsufficientFunds: { balance: bigint };
    };
export type SuspendedReason =
  | {
      /**
       * The minter ignored this UTXO because the UTXO's value is considered too small.
       */
      ValueTooSmall: null;
    }
  | {
      /**
       * The UTXO is considered to be tainted.
       */
      Quarantined: null;
    };
export interface SuspendedUtxo {
  utxo: Utxo;
  earliest_retry: Timestamp;
  reason: SuspendedReason;
}
/**
 * Number of nanoseconds since the Unix Epoch
 */
export type Timestamp = bigint;
export type UpdateBalanceError =
  | {
      /**
       * A generic error reserved for future extensions.
       */
      GenericError: { error_message: string; error_code: bigint };
    }
  | {
      /**
       * The minter is overloaded, retry the request.
       * The payload contains a human-readable message explaining what caused the unavailability.
       */
      TemporarilyUnavailable: string;
    }
  | {
      /**
       * The minter is already processing another update balance request for the caller.
       */
      AlreadyProcessing: null;
    }
  | {
      /**
       * There are no new UTXOs to process.
       */
      NoNewUtxos: {
        suspended_utxos: [] | [Array<SuspendedUtxo>];
        required_confirmations: number;
        pending_utxos: [] | [Array<PendingUtxo>];
        current_confirmations: [] | [number];
      };
    };
/**
 * The upgrade parameters of the minter canister.
 */
export interface UpgradeArgs {
  /**
   * / The expiration duration (in seconds) for cached entries in the get_utxos cache.
   */
  get_utxos_cache_expiration_seconds: [] | [bigint];
  /**
   * The minimal amount of ckDOGE that can be converted to DOGE.
   */
  retrieve_doge_min_amount: [] | [bigint];
  /**
   * / The minter's operation mode.
   */
  mode: [] | [Mode];
  /**
   * / Maximum time in nanoseconds that a transaction should spend in the queue
   * / before being sent.
   */
  max_time_in_queue_nanos: [] | [bigint];
  /**
   * / The maximum number of input UTXOs allowed in a transaction.
   */
  max_num_inputs_in_transaction: [] | [bigint];
  /**
   * / The minimum number of available UTXOs to trigger a consolidation.
   */
  utxo_consolidation_threshold: [] | [bigint];
  /**
   * / The minimum number of confirmations required for the minter to
   * / accept a Dogecoin transaction.
   */
  min_confirmations: [] | [number];
  /**
   * The minimal amount of DOGE that can be converted to ckDOGE.
   * UTXOs with lower values will be ignored.
   */
  deposit_doge_min_amount: [] | [bigint];
}
export interface Utxo {
  height: number;
  value: bigint;
  outpoint: { txid: Uint8Array; vout: number };
}
/**
 * The result of an [update_balance] call.
 */
export type UtxoStatus =
  | {
      /**
       * The minter ignored this UTXO because UTXO's value is too small to pay
       * the check fees.
       */
      ValueTooSmall: Utxo;
    }
  | {
      /**
       * The Dogecoin checker considered this UTXO to be tainted.
       */
      Tainted: Utxo;
    }
  | {
      /**
       * The UTXO passed the Dogecoin check, and ckDOGE has been minted.
       */
      Minted: {
        minted_amount: bigint;
        block_index: bigint;
        utxo: Utxo;
      };
    }
  | {
      /**
       * The UTXO passed the Dogecoin check, but the minter failed to mint ckDOGE
       * because the Ledger was unavailable. Retrying the [update_balance] call
       * should eventually advance the UTXO to the [Minted] state.
       */
      Checked: Utxo;
    };
export interface WithdrawalFee {
  /**
   * Fee paid to the minter for its cycles consumption when building, signing and sending a transaction.
   */
  minter_fee: bigint;
  /**
   * Fee paid to the Dogecoin network to include the transaction in a block.
   */
  dogecoin_fee: bigint;
}
export type WithdrawalReimbursementReason = {
  invalid_transaction: InvalidTransactionError;
};
export interface environment_variable {
  value: string;
  name: string;
}
export type log_visibility =
  | { controllers: null }
  | { public: null }
  | { allowed_viewers: Array<Principal> };
export interface _SERVICE {
  /**
   * / Returns an estimate of the user's fee (in Koinu) for a
   * / retrieve_doge_with_approval request based on the current status of the Dogecoin network.
   */
  estimate_withdrawal_fee: ActorMethod<
    [{ amount: [] | [bigint] }],
    { Ok: WithdrawalFee } | { Err: EstimateWithdrawalFeeError }
  >;
  /**
   * Returns the output of the IC method
   * [`canister_status`](https://internetcomputer.org/docs/references/ic-interface-spec#ic-canister_status)
   */
  get_canister_status: ActorMethod<[], CanisterStatusResponse>;
  /**
   * Returns the Dogecoin address to which the owner should send DOGE
   * before converting the amount to ckDOGE using the [update_balance]
   * endpoint.
   *
   * If the owner is not set, it defaults to the caller's principal.
   * The resolved owner must be a non-anonymous principal.
   */
  get_doge_address: ActorMethod<
    [{ owner: [] | [Principal]; subaccount: [] | [Uint8Array] }],
    string
  >;
  /**
   * The minter keeps track of all state modifications in an internal event log.
   *
   * This method returns a list of events in the specified range.
   * The minter can return fewer events than requested. The result is
   * an empty vector if the start position is greater than the total
   * number of events.
   *
   * NOTE: this method exists for debugging purposes and backwards-compatibility is **not** guaranteed.
   */
  get_events: ActorMethod<[{ start: bigint; length: bigint }], Array<Event>>;
  /**
   * Returns UTXOs of the given account known by the minter (with no
   * guarantee in the ordering of the returned values).
   *
   * If the owner is not set, it defaults to the caller's principal.
   */
  get_known_utxos: ActorMethod<
    [{ owner: [] | [Principal]; subaccount: [] | [Uint8Array] }],
    Array<Utxo>
  >;
  /**
   * Returns internal minter parameters.
   */
  get_minter_info: ActorMethod<[], MinterInfo>;
  /**
   * Returns the status of a withdrawal request.
   */
  retrieve_doge_status: ActorMethod<
    [{ block_index: bigint }],
    RetrieveDogeStatus
  >;
  /**
   * Submits a request to convert ckDOGE to DOGE.
   *
   * # Note
   *
   * The DOGE retrieval process is slow.  Instead of
   * synchronously waiting for a DOGE transaction to settle, this
   * method returns a request ([block_index]) that the caller can use
   * to query the request status.
   *
   * # Preconditions
   *
   * * The caller allowed the minter's principal to spend its funds
   * using [icrc2_approve] on the ckDOGE ledger.
   */
  retrieve_doge_with_approval: ActorMethod<
    [RetrieveDogeWithApprovalArgs],
    { Ok: RetrieveDogeOk } | { Err: RetrieveDogeWithApprovalError }
  >;
  /**
   * Mints ckDOGE for newly deposited UTXOs.
   *
   * If the owner is not set, it defaults to the caller's principal.
   *
   * # Preconditions
   *
   * * The owner deposited some DOGE to the address that the
   * [get_doge_address] endpoint returns.
   */
  update_balance: ActorMethod<
    [{ owner: [] | [Principal]; subaccount: [] | [Uint8Array] }],
    { Ok: Array<UtxoStatus> } | { Err: UpdateBalanceError }
  >;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
