#!/usr/bin/env bash
set -ueo pipefail

# Stop any running dfx processes
dfx killall

dfx start --host 127.0.0.1:4943 --background --clean
dfx deploy

# The principal obtained from the "seed" in the tests/integration/src/utils/identity.ts file
dfx canister call assets authorize '(principal "n7obp-cx27z-e4ytc-ipt7n-urffz-txqa5-el2vn-7vpqc-jjoh3-wrob6-bqe")'
