name: Prepare

description: Checkout and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 25
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      shell: bash
      run: npm ci
