name: Integration Tests

on:
  push:
    branches:
      - main
    paths:
      - 'packages/canisters/src/assets/**'
      - 'tests/integration/**'
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-24.04
    outputs:
      integration: ${{ steps.filter.outputs.integration }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            integration:
              - 'packages/canisters/src/assets/**'
              - 'tests/integration/**'

  test-assets-integration:
    needs: check-changes
    if: needs.check-changes.outputs.integration == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dfinity/setup-dfx@main
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: npm run build
      - name: Test integration
        run: npm run test:integration

  tests-integration-pass:
    if: always()
    needs: ["check-changes", "test-assets-integration"]
    runs-on: ubuntu-24.04
    steps:
      - name: Cleared for merging
        run: |
          if [[ "${{ needs.check-changes.outputs.integration }}" == "true" && "${{ needs.test-assets-integration.result }}" != "success" ]]; then
            exit 1
          fi
